# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Red56
email: info@red56.uk
description: > # this means to ignore newlines until "baseurl:"
  We help SMEs manage their bespoke software
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.red56.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: red56
github_username:  red56

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:day/:title/

theme: minima
kramdown:
  input:          GFM

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 45735    # If you don't want to use the default port
